New Default Setting
inowas/frontend-app pull request #397
Opened 2021-06-08 10:54 UTC by chsprenger

2021-06-09 12:43 UTC, chsprenger commented
Update treatment steps

2021-06-09 18:50 UTC, mrustl commented
@chsprenger you have only pushed your changes we made together yesterday! Maybe there are still some changes still on your laptop?

2021-06-10 07:49 UTC, mrustl commented
Now I am happy! @Roschl have I look how @chsprenger performed!

2021-06-14 18:51 UTC, mrustl commented
@chsprenger you also need to update the https://github.com/inowas/frontend-app/blob/dev/src/scenes/t15/components/defaults/processes.ts in order to be in line with `removals.ts`

2021-06-15 07:01 UTC, chsprenger commented
Si claro, is´ in Mache.

Von: Michael Rustler ***@***.***
Gesendet: Montag, 14. Juni 2021 20:52
An: inowas/frontend-app ***@***.***>
Cc: Christoph Sprenger ***@***.***>; Mention ***@***.***>
Betreff: Re: [inowas/frontend-app] New Default Setting (#397)


@chsprenger<https://github.com/chsprenger> you also need to update the https://github.com/inowas/frontend-app/blob/dev/src/scenes/t15/components/defaults/processes.ts in order to be in line with removals.ts

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/inowas/frontend-app/pull/397#issuecomment-860914135>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALH42DEG6EIB4ELIPMDNGULTSZFTJANCNFSM46JVH75A>.

2021-06-15 09:14 UTC, Roschl commented on src/scenes/t15/components/defaults/processes.ts
>      'TreatmentName': 'Primary treatment',
Did you mix up name and group here?

2021-06-15 09:16 UTC, Roschl commented on src/scenes/t15/components/defaults/processes.ts
> +    'TreatmentGroup': 'Activated sludge',
Same here? Isn't "Activated sludge" the name and not the group?

2021-06-15 09:17 UTC, Roschl requested changes
Please check name vs group (see my comments in the code)

2021-06-16 08:53 UTC, Roschl approved these changes

2021-06-16 08:53 UTC, merged